import '../styles/globals.css'
import type { AppProps } from 'next/app'
import { ChakraProvider } from '@chakra-ui/react'
import {  FilmContextProvider } from '../context/FilmContext'
import Layout from '../components/Layout'
import Head from 'next/head'

export default function App({ Component, pageProps }: AppProps) {
  
  return (
    <>
    <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
    <FilmContextProvider>
      <ChakraProvider>
        <Layout>
        <Component {...pageProps} />
        </Layout>
      </ChakraProvider>
    </FilmContextProvider>
    </>
  )
}
